// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: favorite.proto

package favorite_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FavoriteServiceClient is the client API for FavoriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FavoriteServiceClient interface {
	// Добавить/удалить товар
	ToggleProduct(ctx context.Context, in *ToggleProductRequest, opts ...grpc.CallOption) (*ToggleProductResponse, error)
	// Получить избранное по ID пользователя
	GetFavoriteListById(ctx context.Context, in *GetFavoriteListByIdRequest, opts ...grpc.CallOption) (*GetFavoriteListByIdResponse, error)
}

type favoriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFavoriteServiceClient(cc grpc.ClientConnInterface) FavoriteServiceClient {
	return &favoriteServiceClient{cc}
}

func (c *favoriteServiceClient) ToggleProduct(ctx context.Context, in *ToggleProductRequest, opts ...grpc.CallOption) (*ToggleProductResponse, error) {
	out := new(ToggleProductResponse)
	err := c.cc.Invoke(ctx, "/favorite.FavoriteService/ToggleProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) GetFavoriteListById(ctx context.Context, in *GetFavoriteListByIdRequest, opts ...grpc.CallOption) (*GetFavoriteListByIdResponse, error) {
	out := new(GetFavoriteListByIdResponse)
	err := c.cc.Invoke(ctx, "/favorite.FavoriteService/GetFavoriteListById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FavoriteServiceServer is the server API for FavoriteService service.
// All implementations must embed UnimplementedFavoriteServiceServer
// for forward compatibility
type FavoriteServiceServer interface {
	// Добавить/удалить товар
	ToggleProduct(context.Context, *ToggleProductRequest) (*ToggleProductResponse, error)
	// Получить избранное по ID пользователя
	GetFavoriteListById(context.Context, *GetFavoriteListByIdRequest) (*GetFavoriteListByIdResponse, error)
	mustEmbedUnimplementedFavoriteServiceServer()
}

// UnimplementedFavoriteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFavoriteServiceServer struct {
}

func (UnimplementedFavoriteServiceServer) ToggleProduct(context.Context, *ToggleProductRequest) (*ToggleProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleProduct not implemented")
}
func (UnimplementedFavoriteServiceServer) GetFavoriteListById(context.Context, *GetFavoriteListByIdRequest) (*GetFavoriteListByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFavoriteListById not implemented")
}
func (UnimplementedFavoriteServiceServer) mustEmbedUnimplementedFavoriteServiceServer() {}

// UnsafeFavoriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FavoriteServiceServer will
// result in compilation errors.
type UnsafeFavoriteServiceServer interface {
	mustEmbedUnimplementedFavoriteServiceServer()
}

func RegisterFavoriteServiceServer(s grpc.ServiceRegistrar, srv FavoriteServiceServer) {
	s.RegisterService(&FavoriteService_ServiceDesc, srv)
}

func _FavoriteService_ToggleProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).ToggleProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/favorite.FavoriteService/ToggleProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).ToggleProduct(ctx, req.(*ToggleProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_GetFavoriteListById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoriteListByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).GetFavoriteListById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/favorite.FavoriteService/GetFavoriteListById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).GetFavoriteListById(ctx, req.(*GetFavoriteListByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FavoriteService_ServiceDesc is the grpc.ServiceDesc for FavoriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FavoriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "favorite.FavoriteService",
	HandlerType: (*FavoriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToggleProduct",
			Handler:    _FavoriteService_ToggleProduct_Handler,
		},
		{
			MethodName: "GetFavoriteListById",
			Handler:    _FavoriteService_GetFavoriteListById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "favorite.proto",
}
